weather_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres       # ← ✅ utilise le nom du service Docker !
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public